Src/DeliveryBookingSystem/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DeliveryBookingSystem.Models
{
    public class Customer
    {
        [Key]
        [Display(Name = "Customer Id")]
        public int CustomerId { get; set; }

        [Required(ErrorMessage = "Enter your Name!!")]
        [Display(Name = "Customer Name")]
        public string CustomerName { get; set; }
        [Required(ErrorMessage = "Username cannot be empty!!")]
        [Display(Name = "User Name")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Password cannot be empty!!")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Age cannot be empty!!")]
        public int Age { get; set; }

        [Required(ErrorMessage = "Enter your phone number!!")]
        [MaxLength(10, ErrorMessage = "should be only 10 number and not exceed")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Should be a number!!")]
        public string  Phone { get; set; }

        [Required(ErrorMessage = "Address cannot be empty!!")]
        public string Address { get; set; }

        [Required(ErrorMessage = " enter city!")]
        public string City { get; set; }

        [Required(ErrorMessage = " enter pincode!")]
        public int Pincode { get; set; }

        [Display(Name = " Verified")]
        public string IsVerified { get; set; }

    }
}

Src/DeliveryBookingSystem/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DeliveryBookingSystem.Models;

namespace DeliveryBookingSystem.Controllers
{
    public class BookingsController : Controller
    {
        private readonly CustomerContext _context;

        public BookingsController(CustomerContext context)
        {
            _context = context;
        }

        // GET: Bookings
        public async Task<IActionResult> Index()
        {
            return View(await _context.booking.ToListAsync());
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.booking
                .FirstOrDefaultAsync(m => m.BookingId == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // GET: Bookings/Create
        public IActionResult Create()
        {
            int id = Convert.ToInt32(TempData.Peek("CustomerId"));
            Booking b = new Booking();
            b.CustomerId = id;
            return View(b);
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookingId,CustomerId,ExecutiveId,DateTimeOfPickUp,WeightOfPackage,Address,City,PinCode,Phone,Price,DeliveryStatus")] Booking booking)
        {
            
            if (ModelState.IsValid)
            {
                booking.DeliveryStatus = "Requested";
            //    ViewBag.bookings = dropdown();
                _context.Add(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction("CustomerHome","Customer");
            }
            return View(booking);

        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.booking.FindAsync(id);
            if (booking == null)
            {
                return NotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookingId,CustomerId,ExecutiveId,DateTimeOfPickUp,WeightOfPackage,Address,City,PinCode,Phone,Price,DeliveryStatus")] Booking booking)
        {
            if (id != booking.BookingId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(booking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.BookingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("RequestPending","Executive");
            }
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.booking
                .FirstOrDefaultAsync(m => m.BookingId == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var booking = await _context.booking.FindAsync(id);
        //    _context.booking.Remove(booking);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool BookingExists(int id)
        {
            return _context.booking.Any(e => e.BookingId == id);
        }

        //private List<DeliveryExecutive> dropdown()
        //{
        //    List<DeliveryExecutive> ddl = new List<DeliveryExecutive>();
        //    ddl = (from i in _context.deliveryexecutive
        //           select i).ToList();
        //    return ddl;

        //}
    }
}

Src/DeliveryBookingSystem/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DeliveryBookingSystem.Models;
using DeliveryBookingSystem.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace DeliveryBookingSystem.Controllers
{
    public class CustomerController : Controller
    {

        private readonly CustomerContext _context;
        public readonly ILogger<CustomerController> _logger;
        public readonly IRepo<Customer> _repo;
        public readonly IRepo<Booking> _repo2;
        static List<Customer> cust = new List<Customer>();
        public CustomerController(ILogger<CustomerController> logger, IRepo<Customer> repo,IRepo<Booking> repo2)
        {
            _logger = logger;
            _repo = repo;
            _repo2 =repo2;
        }
        [HttpGet]
        public IActionResult Index()
        {
            List<Customer> customer = _repo.GetAll().ToList();
            return View(customer);
        }

        public IActionResult CustomerList()
        {
            List<Customer> customer = _repo.GetAll().ToList();
            return View(customer);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Customer c)
        {
            c.IsVerified = "Null";
            _repo.Add(c);
            return RedirectToAction("Index");
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Customer c)
        {

            int id = _repo.Login(c);
            if (id != 0)
            {
                TempData["CustomerId"] = id;

                return RedirectToAction("CustomerHome");
            }
            else
            {
                return View("Error");
            }

        }
        public IActionResult TotalList()
        {
            int id = Convert.ToInt32(TempData.Peek("CustomerId"));
            List<Booking> d = _repo2.GetAll().Where(a => a.CustomerId == id).ToList();
            if (d.Count() != 0)
            {
                return View(d);
            }
            else if (d.Count() == 0)
            {
                return View("Empty");
            }
            return View();
        }

        //public ActionResult AcceptList()
        //{
        //    int id = Convert.ToInt32(TempData.Peek("ExecutiveId"));
        //    List<Booking> b = _repo2.GetAll().Where(a => a.ExecutiveId == id && a.DeliveryStatus == "Accepted").ToList();
        //}
        public ActionResult Success()
        {
            return View();
        }
        public ActionResult Error()
        {
            return View();
        }

        public ActionResult CustomerHome()
        {
            return View();
        }
        public IActionResult Edit(int id)
        {
            Customer customer = _repo.Get(id);
            return View(customer);
        }
        [HttpPost]
        public IActionResult Edit(int id, Customer customer)
        {
            _repo.Update(id, customer);
            return RedirectToAction("Index");
        }

        public IActionResult Empty()
        {
            return View();
        }
        
    }
}

Src/DeliveryBookingSystem/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DeliveryBookingSystem.Models;
using Microsoft.AspNetCore.Mvc;

namespace DeliveryBookingSystem.Controllers
{
    public class UserController : Controller
    {
        public ActionResult Register(User u)
        {
            if (u.UserType == "Customer")
            {
                return this.RedirectToAction("Create", "Customer");
            }
            else if (u.UserType == "Executive")
            {
                return this.RedirectToAction("Create", "Executive");
            }
            return View();
        }
        public ActionResult Login(User u)
        {
            if (u.UserType == "Customer")
            {
                return this.RedirectToAction("Login", "Customer");
            }
            else if (u.UserType == "Executive")
            {
                return this.RedirectToAction("Login", "Executive");
            }
            return View();
        }

        public ActionResult Home()
        {
            return View();
        }
    }
}

Src/DeliveryBookingSystem/Views/Customer/Create.cshtml
@model DeliveryBookingSystem.Models.Customer

@{
    ViewData["Title"] = "Create";
}

<h1>Create Customer</h1>
<style>
    body{
        background-color:peachpuff;
    }
</style>
<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                @*<input asp-for="Password" class="form-control" />*@
                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <textarea asp-for="Address" class="form-control"></textarea>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pincode" class="control-label"></label>
                <input asp-for="Pincode" class="form-control" />
                <span asp-validation-for="Pincode" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="IsVerified" class="control-label"></label>
                <input asp-for="IsVerified" class="form-control" />
                <span asp-validation-for="IsVerified" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Move to Customer Index</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Src/DeliveryBookingSystem/Views/Customer/CustomerHome.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<style>
    body{
        background-color:cornsilk;
    }
</style>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="Create">Add Booking</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="TotalList">BookingDetails</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Home">Sign Out</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

Src/DeliveryBookingSystem/Views/Customer/CustomerList.cshtml
@model IEnumerable<DeliveryBookingSystem.Models.Customer>

@{
    ViewData["Title"] = "CustomerList";
}

<h1>CustomerList</h1>
<style>
    body{
        background-color:silver;
        
    }
</style>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.Password)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pincode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsVerified)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pincode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsVerified)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CustomerId">Edit</a> |
                @*<a asp-action="Details" asp-route-id="@item.CustomerId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CustomerId">Delete</a>*@
            </td>
        </tr>
}
    </tbody>
</table>
<div>
    <a asp-action="AdminHomePage" asp-controller="Admin">Back</a>
</div>

Src/DeliveryBookingSystem/Views/Customer/Edit.cshtml
@model DeliveryBookingSystem.Models.Customer

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CustomerId" />
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" readonly />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" readonly />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" readonly />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" readonly/>
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" readonly />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" readonly />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" readonly />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pincode" class="control-label"></label>
                <input asp-for="Pincode" class="form-control" readonly/>
                <span asp-validation-for="Pincode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsVerified" class="control-label"></label>
                <select class="form-control" id="IsVerified" name="IsVerified">
                    <option>Yes</option>
                    <option>No</option>
                </select>
                @*<input asp-for="IsVerified" class="form-control" />
        <span asp-validation-for="IsVerified" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Src/DeliveryBookingSystem/Views/Customer/Empty.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Booking List is empty..</h1>

Src/DeliveryBookingSystem/Views/Customer/Index.cshtml
@model IEnumerable<DeliveryBookingSystem.Models.Customer>

@{
    ViewData["Title"] = "Index";
}

<h1>Customers</h1>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.Password)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pincode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsVerified)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <th>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </th>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pincode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsVerified)
            </td>
            @*<td>
                <a asp-action="Edit" asp-route-id="@item.CustomerId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CustomerId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CustomerId">Delete</a>
            </td>*@
        </tr>
}
    </tbody>
</table>
<div>
    <a asp-action="login">Login Page</a>
</div>

Src/DeliveryBookingSystem/Views/Customer/Login.cshtml
@model DeliveryBookingSystem.Models.Customer

@{
    ViewData["Title"] = "Login";


}

<h1>Login</h1>

<h4>Customer</h4>
<hr />
<style>
    body {
        background-color: #AE956D;
    }
</style>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                    <label asp-for="CustomerName" class="control-label"></label>
                    <input asp-for="CustomerName" class="form-control" />
                    <span asp-validation-for="CustomerName" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                @*<input asp-for="Password" class="form-control" />*@
                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                    <label asp-for="Age" class="control-label"></label>
                    <input asp-for="Age" class="form-control" />
                    <span asp-validation-for="Age" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Phone" class="control-label"></label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label"></label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Pincode" class="control-label"></label>
                    <input asp-for="Pincode" class="form-control" />
                    <span asp-validation-for="Pincode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="IsVerified" class="control-label"></label>
                    <input asp-for="IsVerified" class="form-control" />
                    <span asp-validation-for="IsVerified" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
            <div>If u don't have a account,Register using the given link below</div>
            <div>
                <a asp-action="Create">Register</a>
            </div>
        </form>
    </div>
</div>

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Src/DeliveryBookingSystem/Views/Customer/Success.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Success</h1>
<h2>Welcome!!</h2>

Src/DeliveryBookingSystem/Views/Customer/TotalList.cshtml
@model IEnumerable<DeliveryBookingSystem.Models.Booking>

@{
    ViewData["Title"] = "TotalList";
}

<h1>TotalList</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExecutiveId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateTimeOfPickUp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WeightOfPackage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PinCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryStatus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExecutiveId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTimeOfPickUp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WeightOfPackage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PinCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeliveryStatus)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BookingId">Edit</a> |
                @*<a asp-action="Details" asp-route-id="@item.BookingId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.BookingId">Delete</a>*@
            </td>
        </tr>
}
    </tbody>
</table>
<div>
    <a asp-action="CustomerHome">Back </a>
</div>